# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='carousel_Main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carousel_image', models.ImageField(upload_to=b'')),
                ('carousel_alt', models.TextField(max_length=20)),
            ],
        ),
    ]
