# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0002_carousel_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel_main',
            name='carousel_image',
            field=models.ImageField(upload_to=b'static/images'),
        ),
    ]
